# Example/Documentation for this file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

id: ch.fhir.ig.ch-rad-order
canonical: http://fhir.ch/ig/ch-rad-order
name: CH_RAD_Order
title: "CH RAD-Order (R4)"
description: Implementation guide CH RAD-Order (R4)
status: draft
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2021-01-14
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: HL7 Switzerland
contact:
  name: Juerg P. Bleuer
  telecom:
    system: url
    value: https://www.hl7.ch
dependencies:
  ch.fhir.ig.ch-orf: current
  ch.fhir.ig.ch-core: 2.0.0

pages:
  index.html:
    title: Home
  usecase-english.md:
    title: Use Cases
  usecase-german.md:
    title: Anwendungsf√§lle
  usecase-french.md:
    title: Cas d'application
  questionnaire.html:
    title: Questionnaire
  profiles.html:
    title: Profiles
  extensions.html:
    title: Extensions
  terminology.html:
    title: Terminology